### ISSUE TITLE
Install wallet-recovery-wizzard on ubuntu

### ISSUE THREAD

**Issue by airbornum** [BitGo/wallet-recovery-wizard#23]
When iam start the application on ubuntu.
There are several warnings when compiling:
====
> BitGoWalletRecoveryWizard@1.3.0 start /root/wallet-recovery-wizard
> NODE_ENV=development concurrently 'node scripts/start.js' 'node scripts/electron-wait-react'
Starting the development server...
starting electron
node scripts/electron-wait-react exited with code 0
Compiled with warnings.
./src/constants/nav.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/index.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/views/dashboard/index.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/views/login/index.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/sidebar.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/header.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/error-message.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/main-nav.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/App.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/unsupported-token.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/non-bitgo.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/cross-chain.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/components/form-components.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/constants/tooltips.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/constants/krs-providers.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash
./src/constants/coin-config.js
Line 1:  Definition for rule 'jsx-a11y/href-no-hash' was not found  jsx-a11y/href-no-hash

The application starts, but gives an errors when url in browser:

====
TypeError: window.require is not a function
./src/components/cross-chain.js
src/components/cross-chain.js:27
24 | import jszip from 'jszip';
25 | import * as _ from 'lodash';
26 | 
> 27 | const fs = window.require('fs');
  28 | const { dialog } = window.require('electron').remote;
  29 | const formTooltips = tooltips.crossChain;
  30 | 
View compiled
▶ 2 stack frames were collapsed.
./src/constants/nav.js
src/constants/nav.js:1
> 1 | import CrossChainRecoveryForm from 'components/cross-chain';
  2 | import NonBitGoRecoveryForm from 'components/non-bitgo';
  3 | import UnsupportedTokenRecoveryForm from 'components/unsupported-token';
  4 | 
View compiled

I have use packet version:
os ubuntu 18.04
openssl 1.1.1
npm 6.4.1
nodejs 8.12.0

Can you help me with this problem and is there a possibility to run wallet-recovery-wizard on ubuntu os,  or need to use only mac os?

**Comment by dhoffmann** [comment]
Closing for now. Please open another issue if you continue to see any issues.
