### ISSUE TITLE
Keycard recovery fails

### ISSUE THREAD

**Issue by dabbr** [BitGo/wallet-recovery-wizard#26]
The keycard recovery fails on Windows 10 x64 with something like (very bad guess) 'no sources found' - I'm sorry I'd run it again but I got back into my account and didn't need it.

I tried two keycards (with the A B C D boxes and passcode I knew), same vague error. I changed the passcode to something incorrect and it picked that up.

These were older wallets (Dec 2017). The website, when I got back in, wanted me to update them. I don't know if this is why. Some more human readable output would be good in the tool because it's an end user tool, and hopefully all keycards are supported, and since an error is the one thing keeping user from their 💰, it damn well owes users a better explanation 😜

Also, I had to choose between Testnet and Mainnet, despite the tool saying it doesn't use bitgo. I just chose Mainnet.

This was on latest release exe. I can provide the now empty wallet to someone if a reproduction is needed, though that leaks my wallet password.

Also, the online tool in the other repo doesn't work at all. That's where Google started me.

**Comment by dannybitgo** [comment]
Hello, could you send a screenshot of the error messages you were getting? Despite them being not human-readable, they can help me debug. 

Also if you're willing to share your any more information that would obviously be helpful, but I don't want to encourage you to share your password, so I'll leave that up to you :)

**Comment by dhoffmann** [comment]
Closing for now. Please open another issue if you continue to see any issues.
