### ISSUE TITLE
Recovery key stored GPG keyring?

### ISSUE THREAD

**Issue by anarchymachines** [BitGo/wallet-recovery-wizard#46]
I have a seemingly pretty random issue that isn't necessarily with this software but I'm hoping I can use this software to recover a bitgo wallet I created in early 2016.

I do not have my key card, per se, nor do I remember ever receiving one (although I certainly could have and just forgot). But what I do have is a GPG public/private keypair I found recently on a USB disk titled "Bitgo Key." I have no recollection of creating this, but I did manage to successfully figure out the password protecting it. But I have no idea what my next move should be... If there should even be one. I've tried using the - - list-packets command (with verbose option) and it shows me a lot of info, some of it looking similar to info I have seen in the json blobs of key cards that I've found online (IV, salt, etc) but nothing that seems like a bitcoin key or anything like that. There are four 512 character hex strings in there (when viewed with - -list-packets and -v)  which I think are the public/private keys themselves and respective signatures if I'm not mistaken?

Does it sound like i might have some hope of recovering the wallet? Or am I grasping at straws here? BTW I have the actual account login still, just not the wallet password required to spend the bitcoin.

Any insight you could give would be very much appreciated. Thanks for your time. Let me know if there is any additional info I can provide.

**Comment by dacruz21** [comment]
Hi there!

Could you please send an email to our support team at support@bitgo.com? It sounds like you have a good chance of recovering the wallet if that GPG keypair does in fact store one of the two user keys on your wallet. Our support team will be able to assist you in locating the wallet and building a transaction for them to cosign with the third wallet key, held by BitGo. Please reach out to them over email as they will need to discuss some personal information regarding your account and wallet that would best be discussed somewhere more private.

Thanks!
