### ISSUE TITLE
Installation Error (v2.1.2 Window)

### ISSUE THREAD

**Issue by lee-jisoo** [BitGo/wallet-recovery-wizard#72]
Hello I'am Wallet Developer using Bitgo.com.

V2.1.1 is an installation success, but v2.1.2 generates an error during installation.. 

My System
- os: Windows 10 ver 1903(OS Build 18362.778)
- cpu: Intel(R) Core(TM) i5-8265U CPU 64 Bit os x64 Processor
- BitgoRecoveryWizard V2.1.2
 
Check error message below:
![image](https://user-images.githubusercontent.com/43180334/80382662-7fb5eb00-88dd-11ea-96c0-71eb2db545e8.png)

what was wrong?

**Comment by dhoffmann** [comment]
Please try the latest release: [v2.2.2](https://github.com/BitGo/wallet-recovery-wizard/releases/tag/v2.2.2)

**Comment by dhoffmann** [comment]
Closing for now. Please open another issue if you continue to see any issues.
