### ISSUE TITLE
Export BitGo-Wallet to external Wallet

### ISSUE THREAD

**Issue by HeroHann** [BitGo/wallet-recovery-wizard#76]
Maybe I am not finding the option, but I would like to be able to use a 2 of 3 BitGo-Wallet with Electrum.
With this tool I can create a signed transaction (but not set the fee?) to send all coins to another wallet. But I want to use an online service using BitGo and be able to send transactions with an manual fee. Is that possible? Thanks!

**Comment by glowang** [comment]
Sorry for the late reply! We don't currently support setting your own fee as a feature. But we will create a ticket to track this feature request.
